version: '3.8'

services:
  app:
    build: 
      context: .
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
  
  npm:
    image: node:18-alpine
    entrypoint: ["npm"]
    working_dir: /app
    volumes:
      - ./:/app
